# Project information
site_name: SKT Roleplay wet en regelgeving
site_url: 'https://wetboek.skyroleplay.nl/'
site_description: 'Wet en regelgeving van Tedeapolis roleplay'
site_author: 'Tedeapolis'

# Copyright
copyright: Copyright &copy; 2019 - 2022 SkY

# Repository
repo_url: 'https://github.com/Tedeapolis/wet-en-regelgeving/'
repo_name: 'Tedeapolis/wet-en-regelgeving'
edit_uri: 'https://github.com/Tedeapolis/wet-en-regelgeving/blob/master/docs/'

google_analytics: ['UA-167800475-3', 'wetboek.tedeapolis.nl']

# Congiguration
theme:
  name: material
#   features:
#     - navigation.tabs
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference
  favicon: img/logoTedeapolis.png
  logo: img/logoTedeapolis.webp
  custom_dir: docs/overrides
  language: nl
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - header.autohide
    - toc.follow
  extra:
    analytics:
      provider: google
      property: UA-167800475-3

plugins:
  - git-revision-date-localized:
      type: timeago
      time_zone: Europe/Amsterdam
      locale: nl
      fallback_to_build_date: false
  - search:
      lang: nl
markdown_extensions:
  - admonition
  - attr_list
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js
nav:
  - Home: index.md
  - Algemene Plaatselijke Verordening: apv.md
  - Wetboek: wetboek.md
  - Risicogebieden: risico-gebieden.md
  - Douanegebieden: douanegebieden.md
  - NOTAM: notam.md
  - Belastingen: belastingen.md
  - Regelement voor de rechtspraak: rechtspraak.md
  - Streamen op Tedeapolis: streamen.md
  - Offroad Voertuigen: offroadvoertuigen.md
  - Kosten:
    - Advocatuur: kosten/advocatuur.md
    - Ambulance: kosten/ambulance.md
    - ANWB: kosten/anwb.md
    - Politie: kosten/politie.md
    - Vliegschool: kosten/vliegschool.md
